apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fsb-rev
  name: fsb-rev
  namespace: pwn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fsb-rev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fsb-rev
    spec:
      containers:
      - image: youffes/fsb-rev
        name: fsb-rev
        resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fsb-rev
  name: fsb-rev-service
  namespace: pwn
spec:
  ports:
  - port: 4445
    protocol: TCP
    targetPort: 4445
    nodePort: 30003
  selector:
    app: fripe
  type: NodePort
status:
  loadBalancer: {}

