apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simon
  name: simon
  namespace: pwn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simon
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simon
    spec:
      containers:
      - image: youffes/simon
        name: simon
        resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simon
  name: simon-service
  namespace: pwn
spec:
  ports:
  - port: 4442
    protocol: TCP
    targetPort: 4442
    nodePort: 30004
  selector:
    app: simon
  type: NodePort

